### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by ivasilko** [atlassian/gajira-find-issue-key#5]
My workflow

name: Jira Ticket Key
on:
  pull_request:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    name: Verify Jira Key
    steps:
      - uses: actions/checkout@v1
      - name: Jira login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find ticket key in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: "AO-91 github action for jira"

Error I am getting:
  Find ticket key in commit messages0s
##[error]Node run failed with exit code 1
Run atlassian/gajira-find-issue-key@master
##[error]TypeError: Cannot read property 'join' of undefined
##[error]Node run failed with exit code 1

**Comment by rudzon** [comment]
Hi @ivasilko ! 
The `from` parameter should be one of `commits` or `branch`
You can use `string` parameter to search for keys, like:
```
with:
   string: "AO-91 github action for jira"
```
